permalink: pretty
theme: jekyll_patternbot

patternbot:
  font_url: "https://fonts.googleapis.com/css?family=Lora:400,400i,700|Raleway:400,500,600,700,800,900&display=swap"
  colors:
    background: "--color-neutral-grey"
    patterns:
      brand.logos: "--color-neutral-grey"
